# GNS3 Server Configuration
gns3_server:
  host: "10.2.100.222"
  port: 3080
  protocol: "http"
  # username: ""
  # password: ""

# Project settings
project:
  name: "auto_1"
  
# Template settings
template:
  # The ID of the appliance template to use for all devices
  default_appliance_id: "0da18376-a083-4284-9610-e1f3db7d9344s"