# GNS3 Server Configuration
gns3_server:
  host: "10.2.100.214"
  port: 3080
  protocol: "http"
  # username: ""
  # password: ""

# Project settings
project:
  name: "auto_1"
  position_scale:
    x: 1.2
    y: 1.2
  
# Template settings
template:
  # Default template as fallback
  default_appliance_id: "0da18376-a083-4284-9610-e1f3db7d9344"
  # Family-specific templates
  device_templates:
    #RedFox: "template-id-for-redfox"  
    #Lynx: "template-id-for-lynx"
    #Wolverine: "template-id-for-wolverine"
    #Falcon: "template-id-for-falcon"
  # Optional: More specific model templates
  model_templates:
    #"RedFox-5528-E-F4G-T24G-LV": "template-id-for-specific-model"